"use client"
import SubMenu from '@/components/subMenu'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useState } from 'react';
import { Datas } from '@/helpers/datas'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [openDrawer, setopenDrawer] = useState(false)
  return (
    <html lang="en">
      <body 
      className={inter.className}
      >
        {children}
        <SubMenu items={Datas.submenu} openDrawer={openDrawer} setopenDrawer={setopenDrawer}/>
        </body>
    </html>
  )
}
